spring:
  application:
    name: auth-service

server:
  port: 8081

app:
  jwt:
    issuer: ${JWT_SECRET_ISSUER}
    secret: ${JWT_SECRET}
    refresh-secret: ${JWT_REFRESH_SECRET}
    access-token-expiration: 900000 # 15 minutes in milliseconds (15 * 60 * 1000)
    refresh-token-expiration: 604800000 # 7 days in milliseconds (7 * 24 * 60 * 60 * 1000)
