---
services:
  kong:
    # image: kong:3.9-ubuntu
    build: ./kong
    container_name: kong-gateway
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /etc/kong/kong.yml
      KONG_PROXY_LISTEN: 0.0.0.0:8000
      KONG_PLUGINS: bundled,request-transformer,pre-function,post-function
      KONG_NGINX_MAIN_USER: ""
      JWT_SECRET_ISSUER: ${JWT_SECRET_ISSUER}
      JWT_SECRET: ${JWT_SECRET}
    command: |
      sh -c "envsubst < /etc/kong/kong.yml.template > /etc/kong/kong.yml && kong start"
    ports:
      - "8000:8000"
    volumes:
      - ./kong:/etc/kong
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8081:8081"
    environment:
      - JWT_SECRET_ISSUER=${JWT_SECRET_ISSUER}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
    networks:
      - microservices-net

  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8082:8082"
    environment:
      - JWT_SECRET_ISSUER=${JWT_SECRET_ISSUER}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservices-net

networks:
  microservices-net:
    driver: bridge
